import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { looksLikeSimc, parseSimc } from "./simc.js";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const realDemonHunter = readFileSync(join(FIXTURES, "demonhunter-real.txt"), "utf8");

const HUNTER = `# SimulationCraft Profile
# Generated by SimulationCraft addon

hunter="Bowzo"
level=80
race=blood_elf
region=us
server=area-52
role=attack
professions=skinning=100/leatherworking=100
spec=beast_mastery
talents=CEcAg47sZHMolDr1ETS1pY

head=,id=212019,bonus_id=10421/9633/9627/8902/12053
neck=,id=219339,bonus_id=10876/12053
`;

const DK_WITH_PRELUDE = `# Some addon banner
# blah blah

death_knight="Frosteen"
level=80
race=human
region=eu
server=twisting-nether
spec=frost
`;

const SPACES_IN_NAME = `evoker="Sparkle Pony"
level=80
region=us
server=stormrage
spec=devastation
`;

describe("parseSimc", () => {
    it("parses a hunter export", () => {
        const r = parseSimc(HUNTER);
        expect(r.ok).toBe(true);
        if (!r.ok) return;
        expect(r.character).toMatchObject({
            className: "hunter",
            classDisplay: "Hunter",
            name: "Bowzo",
            region: "us",
            realm: "area-52",
            spec: "beast_mastery",
            level: 80,
            race: "blood_elf",
        });
    });

    it("handles death_knight (underscored class) after a comment prelude", () => {
        const r = parseSimc(DK_WITH_PRELUDE);
        expect(r.ok).toBe(true);
        if (!r.ok) return;
        expect(r.character.className).toBe("death_knight");
        expect(r.character.classDisplay).toBe("Death Knight");
        expect(r.character.region).toBe("eu");
        expect(r.character.realm).toBe("twisting-nether");
    });

    it("preserves unicode-ish names with spaces", () => {
        const r = parseSimc(SPACES_IN_NAME);
        expect(r.ok).toBe(true);
        if (!r.ok) return;
        expect(r.character.name).toBe("Sparkle Pony");
        expect(r.character.className).toBe("evoker");
    });

    it("rejects empty input", () => {
        expect(parseSimc("")).toEqual({ ok: false, error: "Empty input." });
        expect(parseSimc("   \n  \n")).toEqual({ ok: false, error: "Empty input." });
    });

    it("rejects input with no class line", () => {
        const r = parseSimc("level=80\nregion=us\nserver=stormrage\n");
        expect(r.ok).toBe(false);
        if (r.ok) return;
        expect(r.error).toMatch(/class declaration/i);
    });

    it("rejects unknown region", () => {
        const r = parseSimc(`mage="Foo"\nregion=zz\nserver=stormrage\n`);
        expect(r.ok).toBe(false);
        if (r.ok) return;
        expect(r.error).toMatch(/region/i);
    });

    it("rejects missing server", () => {
        const r = parseSimc(`mage="Foo"\nregion=us\nlevel=80\n`);
        expect(r.ok).toBe(false);
        if (r.ok) return;
        expect(r.error).toMatch(/server/i);
    });

    it("parses a real SimC-addon export with `demonhunter` (no underscore)", () => {
        const r = parseSimc(realDemonHunter);
        expect(r.ok).toBe(true);
        if (!r.ok) return;
        expect(r.character).toMatchObject({
            className: "demon_hunter",
            classDisplay: "Demon Hunter",
            name: "Waffledemon",
            region: "us",
            realm: "illidan",
            spec: "devourer",
            level: 90,
            race: "night_elf",
        });
    });

    it("uses the first class line if multiple appear (safety)", () => {
        const r = parseSimc(`hunter="First"\nregion=us\nserver=area-52\nmage="Second"\n`);
        expect(r.ok).toBe(true);
        if (!r.ok) return;
        expect(r.character.name).toBe("First");
        expect(r.character.className).toBe("hunter");
    });
});

describe("looksLikeSimc", () => {
    it("returns true for a real export", () => {
        expect(looksLikeSimc(HUNTER)).toBe(true);
    });
    it("returns false for short chatter", () => {
        expect(looksLikeSimc("hey can you sim me")).toBe(false);
    });
    it("returns false when first non-comment line is not a class line", () => {
        expect(
            looksLikeSimc(
                "# header\nrandom text that is plenty long enough to pass the length check",
            ),
        ).toBe(false);
    });
});
